### ISSUE TITLE
Swagger v2

### ISSUE THREAD

**Issue by eaceto** [unaguil/sphinx-swagger#1]
It only works with Swagger v1 JSON. Not with v2. Is it possible for you to add v2 support?

Also it will be nice if apport from a URL the user can spacify the content of the JSON. Like

.. swaggerdoc::

```
 // here it comes the JSON file
```

Thanks! Great work

**Comment by unaguil** [comment]
Thank you for your feedback. We are migrating some projects to use Swagger v2, so I will update the extension once we start to generate our new documentation.

**Comment by raarts** [comment]
Hi, is there any progress on this? Thanks.

**Comment by moigagoo** [comment]
Hi! Any updates?

**Comment by raarts** [comment]
Apparently @unaguil is working on this. Thanks!

**Comment by unaguil** [comment]
Yes, I need to solve some issues with the new Swagger data.

**Comment by unaguil** [comment]
I have pushed a new version that works with the Swagger 2.0 specification obtained from a remote URL
