### ISSUE TITLE
Unable to process URL for example usage

### ISSUE THREAD

**Issue by pdesjardins** [unaguil/sphinx-swagger#2]
I'm experimenting with this extension and I'm not able to make the examples in the README to work.

I added this to my test RST file:

.. swaggerdoc:: http://petstore.swagger.wordnik.com/api/api-docs/user

Here's what I see in the console output from Sphinx:

Unable to process URL: http://petstore.swagger.wordnik.com/api/api-docs/user

I installed sphinx-swagger from the source I cloned from this repository. I'm using Sphinx v1.2.1 and Python 2.7.10.

Does this sound like misconfiguration or user error? Thanks!

**Comment by senid231** [comment]
same issue here

``` python
def processSwaggerURL(self, url):
    r = requests.get(url)
    return r.json()['apis']
end
```

seems that swagger spec has different syntax
[swagger spec example](http://petstore.swagger.io/v2/swagger.json)

**Comment by unaguil** [comment]
The example URLs are no longer available. The project has been updated to Swagger 2.0 specification
