### ISSUE TITLE
Release for Python3

### ISSUE THREAD

**Issue by gabisurita** [unaguil/sphinx-swagger#7]
The current release on Pypi is only available for Python2. Can you make the release for Python3 as well? (as it works anyways).

https://pypi.python.org/pypi/sphinxcontrib-swaggerdoc/0.1.2

**Comment by hardbyte** [comment]
FYI to make pip install directly from the repository:

```
pip install git+https://github.com/unaguil/sphinx-swaggerdoc.git#egg=sphinxcontrib.swaggerdoc
```

**Comment by gabisurita** [comment]
> FYI to make pip install directly from the repository

But pip install from a repository takes longer (to download the tree) and doesn't allow pinning versions. Since it's already released on Python2 also releasing for Python 3 costs nothing.

**Comment by unaguil** [comment]
I have published a new version into pypi compatible with Python 2 and Python 3
